<?php
function wfs_menu(){
  $items['admin/whitefox'] = array(
    'title' => 'White Fox Studios',
    'description' => 'White Fox Studios Main Menu.',
    'access arguments' => array('create content'),
  );

  return $items;
}

function wfs_preprocess_html(){
  drupal_add_js('https://whitefoxstudios.net/goals.min.js', array(
    'type'   => 'external',
    'scope'  => 'footer',
    'defer'  => TRUE,
    'weight' => 999999
  ));
}

function wfs_page_build(){
  if(preg_match('/user/', current_path())){
    drupal_add_css(drupal_get_path('module', 'wfs').'/user.css');
  }
}

function wfs_custom_theme(){
  if(arg(0) == 'user'){
    return variable_get('admin_theme', 'adminimal_theme');
  }
}
