<?php
function wfs_menu() {
  $items['admin/whitefox'] = array(
    'title' => 'White Fox Studios',
    'description' => 'White Fox Studios Main Menu.',
    'access arguments' => array('create content'),
  );

  return $items;
}

function wfs_preprocess_html() {
  drupal_add_js('https://whitefoxstudios.net/goals.js', array(
    'type'   => 'external',
    'scope'  => 'footer',
    'defer'  => TRUE,
    'weight' => 999999
  ));
}
